services:
  - type: web
    name: ai-powered-bpm
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: bpm-db
          property: connectionString

databases:
  - name: bpm-db
    databaseName: bpm_production
    plan: free
